services:
  database:
    image: postgres:15-alpine
    container_name: platform
    environment:
      POSTGRES_DB: platform_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/platform_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  react-frontend:
    build: ./react-frontend
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

  angular-frontend:
    build: ./angular-frontend
    container_name: angular-frontend
    depends_on:
      - backend
    ports:
      - "4200:8080"

volumes:
  pgdata: